require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL ? { rejectUnauthorized: false } : false
});

async function seedQuestions() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS questions (
      question_id    TEXT PRIMARY KEY,
      level          INTEGER NOT NULL,
      subject        TEXT NOT NULL,
      topic_tag      TEXT NOT NULL,
      q_text_urdu    TEXT NOT NULL,
      q_text_english TEXT,
      option_a       TEXT NOT NULL,
      option_b       TEXT NOT NULL,
      option_c       TEXT NOT NULL,
      option_d       TEXT NOT NULL,
      correct_option TEXT NOT NULL,
      difficulty     INTEGER DEFAULT 1,
      active         INTEGER DEFAULT 1,
      created_at     TIMESTAMP DEFAULT NOW()
    )
  `);

  const questions = [

    // ═══════════════════════════════════════════
    //  MATH — Level 1
    // ═══════════════════════════════════════════

    // ── counting_0_9 ──
    { id:'MTH-L1-001', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'کون سا نمبر 5 کے بعد آتا ہے؟', en:'Which number comes after 5?',
      a:'4', b:'6', c:'7', d:'8', ans:'B' },
    { id:'MTH-L1-002', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'کون سا نمبر 3 سے پہلے آتا ہے؟', en:'Which number comes before 3?',
      a:'4', b:'2', c:'1', d:'5', ans:'B' },
    { id:'MTH-L1-003', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'ان میں سب سے بڑا نمبر کون سا ہے: 3، 7، 1، 5؟', en:'Which is the largest: 3, 7, 1, 5?',
      a:'3', b:'1', c:'5', d:'7', ans:'D' },
    { id:'MTH-L1-004', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'ان میں سب سے چھوٹا نمبر کون سا ہے: 2، 8، 5، 4؟', en:'Which is the smallest: 2, 8, 5, 4?',
      a:'2', b:'8', c:'5', d:'4', ans:'A' },
    { id:'MTH-L1-005', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'8 کے بعد کیا آتا ہے؟', en:'What comes after 8?',
      a:'6', b:'7', c:'9', d:'10', ans:'C' },
    { id:'MTH-L1-006', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'7 سے پہلے کیا آتا ہے؟', en:'What comes before 7?',
      a:'8', b:'5', c:'6', d:'9', ans:'C' },
    { id:'MTH-L1-007', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'4 اور 6 کے درمیان کون سا نمبر ہے؟', en:'Which number is between 4 and 6?',
      a:'3', b:'7', c:'5', d:'8', ans:'C' },
    { id:'MTH-L1-008', level:1, subject:'Math', topic:'counting_0_9', difficulty:1,
      ur:'ایک ہاتھ میں کتنی انگلیاں ہوتی ہیں؟', en:'How many fingers on one hand?',
      a:'3', b:'4', c:'5', d:'6', ans:'C' },
    { id:'MTH-L1-009', level:1, subject:'Math', topic:'counting_0_9', difficulty:2,
      ur:'6، 7، 8 کے بعد کیا آتا ہے؟', en:'After 6, 7, 8 comes?',
      a:'10', b:'9', c:'11', d:'5', ans:'B' },
    { id:'MTH-L1-010', level:1, subject:'Math', topic:'counting_0_9', difficulty:2,
      ur:'1، 2، 3، 4، ___ : خالی جگہ پُر کریں', en:'1, 2, 3, 4, ___',
      a:'6', b:'3', c:'5', d:'7', ans:'C' },

    // ── concept_of_zero ──
    { id:'MTH-L1-011', level:1, subject:'Math', topic:'concept_of_zero', difficulty:1,
      ur:'صفر کا مطلب کیا ہے؟', en:'Zero means?',
      a:'ایک', b:'کچھ نہیں', c:'دس', d:'پانچ', ans:'B' },
    { id:'MTH-L1-012', level:1, subject:'Math', topic:'concept_of_zero', difficulty:1,
      ur:'اگر آپ کے پاس 3 سیب ہیں اور سب کھا لیں تو کتنے بچیں گے؟', en:'If you have 3 apples and eat all, how many remain?',
      a:'1', b:'2', c:'3', d:'0', ans:'D' },
    { id:'MTH-L1-013', level:1, subject:'Math', topic:'concept_of_zero', difficulty:1,
      ur:'کون سا نمبر 1 سے چھوٹا ہے؟', en:'Which number is less than 1?',
      a:'2', b:'3', c:'0', d:'4', ans:'C' },
    { id:'MTH-L1-014', level:1, subject:'Math', topic:'concept_of_zero', difficulty:1,
      ur:'0 + 5 = ؟', en:'0 + 5 = ?',
      a:'0', b:'1', c:'5', d:'50', ans:'C' },
    { id:'MTH-L1-015', level:1, subject:'Math', topic:'concept_of_zero', difficulty:2,
      ur:'کون سا صحیح ہے؟', en:'Which is correct?',
      a:'0 > 1', b:'0 < 1', c:'0 = 1', d:'0 > 5', ans:'B' },
    { id:'MTH-L1-016', level:1, subject:'Math', topic:'concept_of_zero', difficulty:1,
      ur:'صفر رنگ بھرنا — اس کی شکل کیسی ہے؟', en:'Zero looks like which shape?',
      a:'مثلث', b:'مربع', c:'دائرہ', d:'ستارہ', ans:'C' },

    // ── place_value_11_19 ──
    { id:'MTH-L1-017', level:1, subject:'Math', topic:'place_value_11_19', difficulty:1,
      ur:'15 کے بعد کون سا نمبر آتا ہے؟', en:'Which number comes after 15?',
      a:'14', b:'16', c:'17', d:'18', ans:'B' },
    { id:'MTH-L1-018', level:1, subject:'Math', topic:'place_value_11_19', difficulty:1,
      ur:'13 میں کتنی داہائیاں ہیں؟', en:'How many tens in 13?',
      a:'3', b:'1', c:'2', d:'0', ans:'B' },
    { id:'MTH-L1-019', level:1, subject:'Math', topic:'place_value_11_19', difficulty:1,
      ur:'17 میں کتنی اکائیاں ہیں؟', en:'How many units in 17?',
      a:'1', b:'7', c:'8', d:'17', ans:'B' },
    { id:'MTH-L1-020', level:1, subject:'Math', topic:'place_value_11_19', difficulty:2,
      ur:'1 داہائی اور 6 اکائیاں کون سا نمبر بناتی ہیں؟', en:'1 ten and 6 units make which number?',
      a:'61', b:'16', c:'26', d:'11', ans:'B' },
    { id:'MTH-L1-021', level:1, subject:'Math', topic:'place_value_11_19', difficulty:1,
      ur:'19 سے پہلے کیا آتا ہے؟', en:'What comes before 19?',
      a:'20', b:'17', c:'18', d:'11', ans:'C' },
    { id:'MTH-L1-022', level:1, subject:'Math', topic:'place_value_11_19', difficulty:1,
      ur:'12 اور 14 کے درمیان کیا ہے؟', en:'What is between 12 and 14?',
      a:'11', b:'15', c:'13', d:'10', ans:'C' },
    { id:'MTH-L1-023', level:1, subject:'Math', topic:'place_value_11_19', difficulty:2,
      ur:'18 میں اکائی کا ہندسہ کون سا ہے؟', en:'In 18, which digit is in units place?',
      a:'1', b:'18', c:'8', d:'0', ans:'C' },

    // ── place_value_20_99 ──
    { id:'MTH-L1-024', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'29 کے بعد کیا آتا ہے؟', en:'What comes after 29?',
      a:'28', b:'30', c:'31', d:'20', ans:'B' },
    { id:'MTH-L1-025', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'35 میں کتنی داہائیاں ہیں؟', en:'How many tens in 35?',
      a:'5', b:'3', c:'8', d:'35', ans:'B' },
    { id:'MTH-L1-026', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'42 میں کتنی اکائیاں ہیں؟', en:'How many units in 42?',
      a:'4', b:'2', c:'6', d:'42', ans:'B' },
    { id:'MTH-L1-027', level:1, subject:'Math', topic:'place_value_20_99', difficulty:2,
      ur:'4 داہائیاں اور 7 اکائیاں کون سا نمبر ہے؟', en:'4 tens and 7 units = which number?',
      a:'74', b:'47', c:'4', d:'7', ans:'B' },
    { id:'MTH-L1-028', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'50 سے پہلے کیا آتا ہے؟', en:'What comes before 50?',
      a:'51', b:'49', c:'48', d:'52', ans:'B' },
    { id:'MTH-L1-029', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'69 کے بعد کیا آتا ہے؟', en:'What comes after 69?',
      a:'68', b:'70', c:'71', d:'60', ans:'B' },
    { id:'MTH-L1-030', level:1, subject:'Math', topic:'place_value_20_99', difficulty:2,
      ur:'ان میں سب سے چھوٹا: 72، 85، 63، 91؟', en:'Smallest of: 72, 85, 63, 91?',
      a:'85', b:'72', c:'91', d:'63', ans:'D' },
    { id:'MTH-L1-031', level:1, subject:'Math', topic:'place_value_20_99', difficulty:1,
      ur:'97 اور 99 کے درمیان کیا ہے؟', en:'What is between 97 and 99?',
      a:'96', b:'100', c:'98', d:'95', ans:'C' },
    { id:'MTH-L1-032', level:1, subject:'Math', topic:'place_value_20_99', difficulty:2,
      ur:'75 میں داہائی کا ہندسہ کون سا ہے؟', en:'In 75, which digit is in tens place?',
      a:'5', b:'7', c:'12', d:'75', ans:'B' },

    // ── number_100 ──
    { id:'MTH-L1-033', level:1, subject:'Math', topic:'number_100', difficulty:1,
      ur:'99 کے بعد کیا آتا ہے؟', en:'What comes after 99?',
      a:'98', b:'100', c:'101', d:'90', ans:'B' },
    { id:'MTH-L1-034', level:1, subject:'Math', topic:'number_100', difficulty:1,
      ur:'100 میں کتنی داہائیاں ہیں؟', en:'How many tens are in 100?',
      a:'1', b:'10', c:'100', d:'0', ans:'B' },
    { id:'MTH-L1-035', level:1, subject:'Math', topic:'number_100', difficulty:1,
      ur:'100 میں کتنے صفر ہیں؟', en:'How many zeros in 100?',
      a:'1', b:'2', c:'3', d:'0', ans:'B' },
    { id:'MTH-L1-036', level:1, subject:'Math', topic:'number_100', difficulty:1,
      ur:'99 اور 100 میں سے بڑا کون ہے؟', en:'Which is greater: 99 or 100?',
      a:'99', b:'100', c:'برابر', d:'کوئی نہیں', ans:'B' },
    { id:'MTH-L1-037', level:1, subject:'Math', topic:'number_100', difficulty:2,
      ur:'100 = ___ داہائیاں + ___ اکائیاں', en:'100 = ___ tens + ___ units',
      a:'10 داہائی، 0 اکائی', b:'1 داہائی، 0 اکائی', c:'0 داہائی، 100 اکائی', d:'100 داہائی', ans:'A' },

    // ── ascending_order ──
    { id:'MTH-L1-038', level:1, subject:'Math', topic:'ascending_order', difficulty:1,
      ur:'ترتیب بڑھتی (چھوٹے سے بڑے) کون سی ہے؟', en:'Which is ascending order (small to large)?',
      a:'9،7،5،3', b:'1،3،5،7', c:'5،3،1،9', d:'7،9،3،5', ans:'B' },
    { id:'MTH-L1-039', level:1, subject:'Math', topic:'ascending_order', difficulty:1,
      ur:'بڑھتی ترتیب کا مطلب کیا ہے؟', en:'Ascending order means?',
      a:'بڑے سے چھوٹے', b:'چھوٹے سے بڑے', c:'بے ترتیب', d:'برابر', ans:'B' },
    { id:'MTH-L1-040', level:1, subject:'Math', topic:'ascending_order', difficulty:2,
      ur:'10، 20، 30 کے بعد کیا آئے گا؟', en:'10, 20, 30, ___?',
      a:'25', b:'35', c:'40', d:'50', ans:'C' },
    { id:'MTH-L1-041', level:1, subject:'Math', topic:'ascending_order', difficulty:2,
      ur:'15، 8، 23، 4 کو بڑھتی ترتیب میں لکھیں', en:'Arrange 15, 8, 23, 4 in ascending order',
      a:'4،8،15،23', b:'23،15،8،4', c:'8،4،23،15', d:'15،23،4،8', ans:'A' },
    { id:'MTH-L1-042', level:1, subject:'Math', topic:'ascending_order', difficulty:1,
      ur:'کون سی ترتیب صحیح بڑھتی ترتیب ہے؟', en:'Which is correct ascending order?',
      a:'5،10،15،20', b:'20،15،10،5', c:'5،20،10،15', d:'15،5،20،10', ans:'A' },

    // ── descending_order ──
    { id:'MTH-L1-043', level:1, subject:'Math', topic:'descending_order', difficulty:1,
      ur:'گھٹتی ترتیب (بڑے سے چھوٹے) کون سی ہے؟', en:'Which is descending order (large to small)?',
      a:'1،3،5،7', b:'9،7،5،3', c:'3،7،1،9', d:'5،3،9،7', ans:'B' },
    { id:'MTH-L1-044', level:1, subject:'Math', topic:'descending_order', difficulty:1,
      ur:'گھٹتی ترتیب کا مطلب؟', en:'Descending order means?',
      a:'چھوٹے سے بڑے', b:'بڑے سے چھوٹے', c:'برابر', d:'بے ترتیب', ans:'B' },
    { id:'MTH-L1-045', level:1, subject:'Math', topic:'descending_order', difficulty:2,
      ur:'50، 40، 30، ___ : اگلا نمبر؟', en:'50, 40, 30, ___?',
      a:'35', b:'25', c:'20', d:'10', ans:'C' },
    { id:'MTH-L1-046', level:1, subject:'Math', topic:'descending_order', difficulty:2,
      ur:'7، 2، 9، 4 کو گھٹتی ترتیب میں لکھیں', en:'Arrange 7, 2, 9, 4 in descending order',
      a:'2،4،7،9', b:'9،7،4،2', c:'4،9،2،7', d:'7،2،9،4', ans:'B' },
    { id:'MTH-L1-047', level:1, subject:'Math', topic:'descending_order', difficulty:2,
      ur:'100، 90، 80، ___ : اگلا؟', en:'100, 90, 80, ___?',
      a:'85', b:'75', c:'70', d:'60', ans:'C' },

    // ── ones_and_tens ──
    { id:'MTH-L1-048', level:1, subject:'Math', topic:'ones_and_tens', difficulty:1,
      ur:'46 میں داہائی کا ہندسہ؟', en:'In 46, which digit is in tens place?',
      a:'6', b:'4', c:'46', d:'0', ans:'B' },
    { id:'MTH-L1-049', level:1, subject:'Math', topic:'ones_and_tens', difficulty:1,
      ur:'28 میں اکائی کا ہندسہ؟', en:'In 28, which digit is in units place?',
      a:'2', b:'28', c:'8', d:'0', ans:'C' },
    { id:'MTH-L1-050', level:1, subject:'Math', topic:'ones_and_tens', difficulty:2,
      ur:'3 داہائی اور 5 اکائی = ؟', en:'3 tens and 5 units = ?',
      a:'35', b:'53', c:'305', d:'8', ans:'A' },
    { id:'MTH-L1-051', level:1, subject:'Math', topic:'ones_and_tens', difficulty:2,
      ur:'7 اکائی اور 4 داہائی = ؟', en:'7 units and 4 tens = ?',
      a:'74', b:'47', c:'7', d:'4', ans:'B' },
    { id:'MTH-L1-052', level:1, subject:'Math', topic:'ones_and_tens', difficulty:2,
      ur:'435 میں سینکڑے کا ہندسہ؟', en:'In 435, which digit is in hundreds place?',
      a:'4', b:'3', c:'5', d:'0', ans:'A' },
    { id:'MTH-L1-053', level:1, subject:'Math', topic:'ones_and_tens', difficulty:2,
      ur:'867 میں اکائی کا ہندسہ؟', en:'In 867, which digit is in units place?',
      a:'8', b:'6', c:'7', d:'0', ans:'C' },
    { id:'MTH-L1-054', level:1, subject:'Math', topic:'ones_and_tens', difficulty:1,
      ur:'91 میں داہائی کا ہندسہ؟', en:'In 91, which digit is in tens place?',
      a:'1', b:'91', c:'9', d:'10', ans:'C' },

    // ── before_after_middle ──
    { id:'MTH-L1-055', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'25 سے پہلے کیا آتا ہے؟', en:'What comes before 25?',
      a:'26', b:'24', c:'23', d:'20', ans:'B' },
    { id:'MTH-L1-056', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'47 کے بعد کیا آتا ہے؟', en:'What comes after 47?',
      a:'46', b:'48', c:'49', d:'50', ans:'B' },
    { id:'MTH-L1-057', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'10، ___، 12 : درمیانی نمبر؟', en:'Middle number: 10, ___, 12?',
      a:'9', b:'13', c:'11', d:'14', ans:'C' },
    { id:'MTH-L1-058', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'35 اور 37 کے درمیان کیا ہے؟', en:'What is between 35 and 37?',
      a:'34', b:'38', c:'36', d:'33', ans:'C' },
    { id:'MTH-L1-059', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'19 کے بعد کیا آتا ہے؟', en:'What comes after 19?',
      a:'18', b:'21', c:'20', d:'22', ans:'C' },
    { id:'MTH-L1-060', level:1, subject:'Math', topic:'before_after_middle', difficulty:1,
      ur:'6، ___، 8 : درمیانی نمبر؟', en:'Middle of 6, ___, 8?',
      a:'5', b:'9', c:'7', d:'10', ans:'C' },

    // ── comparison ──
    { id:'MTH-L1-061', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'کس گروپ میں زیادہ ہیں: 5 سیب یا 3 سیب؟', en:'Which group has more: 5 apples or 3 apples?',
      a:'3 سیب', b:'5 سیب', c:'برابر', d:'کوئی نہیں', ans:'B' },
    { id:'MTH-L1-062', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'7 کس سے بڑا ہے؟', en:'7 is greater than?',
      a:'8', b:'9', c:'6', d:'10', ans:'C' },
    { id:'MTH-L1-063', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'4 کس سے چھوٹا ہے؟', en:'4 is less than?',
      a:'3', b:'2', c:'1', d:'5', ans:'D' },
    { id:'MTH-L1-064', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'5 ___ 3 : درست نشان لگائیں', en:'5 ___ 3: correct sign?',
      a:'<', b:'>', c:'=', d:'+', ans:'B' },
    { id:'MTH-L1-065', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'2 ___ 7 : درست نشان؟', en:'2 ___ 7: correct sign?',
      a:'>', b:'=', c:'<', d:'+', ans:'C' },
    { id:'MTH-L1-066', level:1, subject:'Math', topic:'comparison', difficulty:1,
      ur:'کس گروپ میں کم ہیں: 8 ستارے یا 5 ستارے؟', en:'Which has fewer: 8 stars or 5 stars?',
      a:'8 ستارے', b:'5 ستارے', c:'برابر', d:'دونوں', ans:'B' },

    // ── ordinal_numbers ──
    { id:'MTH-L1-067', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'1st کا مطلب؟', en:'1st means?',
      a:'دوسرا', b:'تیسرا', c:'پہلا', d:'چوتھا', ans:'C' },
    { id:'MTH-L1-068', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'2nd کا مطلب؟', en:'2nd means?',
      a:'پہلا', b:'دوسرا', c:'تیسرا', d:'چوتھا', ans:'B' },
    { id:'MTH-L1-069', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'"Third" نمبروں میں کیا ہے؟', en:'"Third" in numbers is?',
      a:'1st', b:'4th', c:'3rd', d:'2nd', ans:'C' },
    { id:'MTH-L1-070', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'"Seventh" نمبروں میں کیا ہے؟', en:'"Seventh" in numbers is?',
      a:'5th', b:'6th', c:'8th', d:'7th', ans:'D' },
    { id:'MTH-L1-071', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'9th کا مطلب؟', en:'9th means?',
      a:'ninth', b:'seventh', c:'eighth', d:'tenth', ans:'A' },
    { id:'MTH-L1-072', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'"Second" نمبروں میں کیا ہے؟', en:'"Second" in numbers is?',
      a:'3rd', b:'1st', c:'2nd', d:'4th', ans:'C' },
    { id:'MTH-L1-073', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:1,
      ur:'10th کا مطلب؟', en:'10th means?',
      a:'ninth', b:'eighth', c:'tenth', d:'eleventh', ans:'C' },
    { id:'MTH-L1-074', level:1, subject:'Math', topic:'ordinal_numbers', difficulty:2,
      ur:'5th کو الفاظ میں لکھیں', en:'5th in words is?',
      a:'fourth', b:'sixth', c:'third', d:'fifth', ans:'D' },

    // ═══════════════════════════════════════════
    //  ENGLISH — Level 1
    // ═══════════════════════════════════════════

    // ── short_vowel_a ──
    { id:'ENG-L1-001', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'کون سے لفظ میں "a" کی چھوٹی آواز ہے؟', en:'Which word has the short "a" sound?',
      a:'bite', b:'cat', c:'tree', d:'cube', ans:'B' },
    { id:'ENG-L1-002', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'"bat" کے ساتھ ہم قافیہ کون سا ہے؟', en:'"bat" rhymes with?',
      a:'bit', b:'but', c:'mat', d:'met', ans:'C' },
    { id:'ENG-L1-003', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'"hat" میں "a" کی آواز کیسی ہے؟', en:'The "a" in "hat" is?',
      a:'long a', b:'short a', c:'long e', d:'short i', ans:'B' },
    { id:'ENG-L1-004', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'c + a + t = ؟', en:'c + a + t = ?',
      a:'cut', b:'cot', c:'cat', d:'kit', ans:'C' },
    { id:'ENG-L1-005', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'آپ سر پر کیا پہنتے ہیں؟ (3 حروف)', en:'You wear it on your head (3 letters)?',
      a:'mat', b:'rat', c:'hat', d:'bat', ans:'C' },
    { id:'ENG-L1-006', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'آپ جس پر بیٹھتے ہیں: mat، bat، rat — کون سا؟', en:'You sit/sleep on a?',
      a:'bat', b:'rat', c:'cat', d:'mat', ans:'D' },
    { id:'ENG-L1-007', level:1, subject:'English', topic:'short_vowel_a', difficulty:2,
      ur:'"hat" کے ساتھ ہم قافیہ؟', en:'"hat" rhymes with?',
      a:'hot', b:'hit', c:'bat', d:'bit', ans:'C' },
    { id:'ENG-L1-008', level:1, subject:'English', topic:'short_vowel_a', difficulty:1,
      ur:'ایک چھوٹا جانور جو پنجرے میں ہوتا ہے (3 حروف)؟', en:'Small furry creature (3 letters)?',
      a:'cat', b:'bat', c:'rat', d:'mat', ans:'C' },

    // ── short_vowel_e ──
    { id:'ENG-L1-009', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'کون سے لفظ میں "e" کی چھوٹی آواز ہے؟', en:'Which has short "e" sound?',
      a:'tree', b:'feel', c:'hen', d:'he', ans:'C' },
    { id:'ENG-L1-010', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'"pen" کے ساتھ ہم قافیہ؟', en:'"pen" rhymes with?',
      a:'pin', b:'pan', c:'pun', d:'ten', ans:'D' },
    { id:'ENG-L1-011', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'9 کے بعد کا نمبر (لفظ میں)؟', en:'The number after 9 in words?',
      a:'hen', b:'men', c:'ten', d:'pen', ans:'C' },
    { id:'ENG-L1-012', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'مادہ مرغی کو کیا کہتے ہیں؟', en:'A female chicken is called?',
      a:'men', b:'pen', c:'hen', d:'ten', ans:'C' },
    { id:'ENG-L1-013', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'لکھنے کے لیے کیا استعمال کرتے ہیں؟', en:'You write with a?',
      a:'hen', b:'men', c:'ten', d:'pen', ans:'D' },
    { id:'ENG-L1-014', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'"red" کیا ہے؟', en:'"red" is a?',
      a:'number', b:'animal', c:'color', d:'shape', ans:'C' },
    { id:'ENG-L1-015', level:1, subject:'English', topic:'short_vowel_e', difficulty:2,
      ur:'h + e + n = ؟', en:'h + e + n = ?',
      a:'han', b:'hin', c:'hun', d:'hen', ans:'D' },
    { id:'ENG-L1-016', level:1, subject:'English', topic:'short_vowel_e', difficulty:1,
      ur:'کون سے لفظ میں چھوٹی "e" ہے؟', en:'Which has short "e"?',
      a:'meet', b:'red', c:'feed', d:'tree', ans:'B' },

    // ── short_vowel_i ──
    { id:'ENG-L1-017', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'کون سے لفظ میں "i" کی چھوٹی آواز ہے؟', en:'Which has short "i" sound?',
      a:'bite', b:'kite', c:'fish', d:'five', ans:'C' },
    { id:'ENG-L1-018', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'5 کے بعد کا نمبر (لفظ میں)؟', en:'Number after 5 in words?',
      a:'six', b:'zip', c:'big', d:'pin', ans:'A' },
    { id:'ENG-L1-019', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'پانی میں تیرتا ہے؟', en:'It swims in water?',
      a:'zip', b:'pin', c:'fish', d:'big', ans:'C' },
    { id:'ENG-L1-020', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'"big" کا مطلب؟', en:'"big" means?',
      a:'small', b:'short', c:'large', d:'thin', ans:'C' },
    { id:'ENG-L1-021', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'b + i + g = ؟', en:'b + i + g = ?',
      a:'bag', b:'bug', c:'big', d:'bog', ans:'C' },
    { id:'ENG-L1-022', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'کاغذ اکٹھے رکھنے کے لیے کیا استعمال کریں؟', en:'You use a ___ to hold papers together?',
      a:'zip', b:'pin', c:'six', d:'fish', ans:'B' },
    { id:'ENG-L1-023', level:1, subject:'English', topic:'short_vowel_i', difficulty:1,
      ur:'کون سے لفظ میں چھوٹی "i" ہے؟', en:'Which has short "i"?',
      a:'kite', b:'bike', c:'six', d:'hide', ans:'C' },

    // ── short_vowel_o ──
    { id:'ENG-L1-024', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'کون سے لفظ میں "o" کی چھوٹی آواز ہے؟', en:'Which has short "o" sound?',
      a:'rose', b:'hose', c:'frog', d:'bone', ans:'C' },
    { id:'ENG-L1-025', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'بڑا جانور جو گاڑی کھینچتا ہے؟', en:'Large animal that pulls carts?',
      a:'frog', b:'dog', c:'ox', d:'box', ans:'C' },
    { id:'ENG-L1-026', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'چیزیں اس میں رکھتے ہیں؟', en:'You put things inside a?',
      a:'frog', b:'dog', c:'hot', d:'box', ans:'D' },
    { id:'ENG-L1-027', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'ٹھنڈے کا الٹ؟', en:'Opposite of cold?',
      a:'frog', b:'box', c:'hot', d:'ox', ans:'C' },
    { id:'ENG-L1-028', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'f + r + o + g = ؟', en:'f + r + o + g = ?',
      a:'frag', b:'frug', c:'frog', d:'frig', ans:'C' },
    { id:'ENG-L1-029', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'انسان کا وفادار دوست (جانور)؟', en:"Man's best friend (animal)?",
      a:'frog', b:'dog', c:'ox', d:'box', ans:'B' },
    { id:'ENG-L1-030', level:1, subject:'English', topic:'short_vowel_o', difficulty:1,
      ur:'کون سے لفظ میں چھوٹی "o" ہے؟', en:'Which has short "o"?',
      a:'rope', b:'rose', c:'hot', d:'hose', ans:'C' },

    // ── short_vowel_u ──
    { id:'ENG-L1-031', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'کون سے لفظ میں "u" کی چھوٹی آواز ہے؟', en:'Which has short "u" sound?',
      a:'cube', b:'tube', c:'cup', d:'tune', ans:'C' },
    { id:'ENG-L1-032', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'آپ اس میں سے پیتے ہیں؟', en:'You drink from a?',
      a:'bus', b:'jug', c:'cup', d:'plug', ans:'C' },
    { id:'ENG-L1-033', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'بہت سے لوگوں کے لیے بڑی گاڑی؟', en:'Large vehicle for many people?',
      a:'cup', b:'jug', c:'plug', d:'bus', ans:'D' },
    { id:'ENG-L1-034', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'روشنی اور گرمی دیتا ہے؟', en:'It gives us light and heat?',
      a:'plug', b:'cup', c:'jug', d:'sun', ans:'D' },
    { id:'ENG-L1-035', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'j + u + g = ؟', en:'j + u + g = ?',
      a:'jag', b:'jog', c:'jig', d:'jug', ans:'D' },
    { id:'ENG-L1-036', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'مائع کے لیے بڑا برتن؟', en:'A large container for liquids?',
      a:'cup', b:'bus', c:'jug', d:'plug', ans:'C' },
    { id:'ENG-L1-037', level:1, subject:'English', topic:'short_vowel_u', difficulty:1,
      ur:'کون سے لفظ میں چھوٹی "u" ہے؟', en:'Which has short "u"?',
      a:'June', b:'tune', c:'sun', d:'cute', ans:'C' },

    // ── long_vowel_a ──
    { id:'ENG-L1-038', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'کون سے لفظ میں "a" کی لمبی آواز ہے؟', en:'Which has long "a" sound?',
      a:'cat', b:'cake', c:'cap', d:'can', ans:'B' },
    { id:'ENG-L1-039', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'سالگرہ پر یہ میٹھا ہوتا ہے؟', en:'Sweet on birthday?',
      a:'gate', b:'snake', c:'cake', d:'grape', ans:'C' },
    { id:'ENG-L1-040', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'آپ اس سے اندر جاتے ہیں؟', en:'You enter through a?',
      a:'cake', b:'grape', c:'snake', d:'gate', ans:'D' },
    { id:'ENG-L1-041', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'گچھوں میں اگنے والا چھوٹا پھل؟', en:'Small fruit growing in clusters?',
      a:'gate', b:'cake', c:'grape', d:'cage', ans:'C' },
    { id:'ENG-L1-042', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'رینگنے والا جانور؟', en:'A reptile that slithers?',
      a:'gate', b:'cake', c:'cage', d:'snake', ans:'D' },
    { id:'ENG-L1-043', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'پرندے اس میں رہتے ہیں؟', en:'Birds live in a?',
      a:'snake', b:'gate', c:'cage', d:'grape', ans:'C' },
    { id:'ENG-L1-044', level:1, subject:'English', topic:'long_vowel_a', difficulty:1,
      ur:'لمبی "a" کی آواز کون سے لفظ میں ہے؟', en:'Which has long "a"?',
      a:'hat', b:'gate', c:'bat', d:'map', ans:'B' },

    // ── long_vowel_e ──
    { id:'ENG-L1-045', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'کون سے لفظ میں "e" کی لمبی آواز ہے؟', en:'Which has long "e" sound?',
      a:'red', b:'hen', c:'tree', d:'net', ans:'C' },
    { id:'ENG-L1-046', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'آپ اسے بازو پر پہنتے ہیں؟', en:'You wear it on your arm?',
      a:'cheese', b:'tree', c:'sleeve', d:'freeze', ans:'C' },
    { id:'ENG-L1-047', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'دودھ سے بنتا ہے؟', en:'Made from milk?',
      a:'tree', b:'scene', c:'freeze', d:'cheese', ans:'D' },
    { id:'ENG-L1-048', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'سایہ اور پھل دیتا ہے؟', en:'Gives shade and fruit?',
      a:'sleeve', b:'tree', c:'scene', d:'freeze', ans:'B' },
    { id:'ENG-L1-049', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'"ee" کی آواز؟', en:'"ee" makes which sound?',
      a:'short e', b:'long e', c:'short a', d:'long a', ans:'B' },
    { id:'ENG-L1-050', level:1, subject:'English', topic:'long_vowel_e', difficulty:1,
      ur:'کون سے لفظ میں لمبی "e" ہے؟', en:'Which has long "e"?',
      a:'net', b:'bed', c:'tree', d:'red', ans:'C' },

    // ── long_vowel_i ──
    { id:'ENG-L1-051', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'کون سے لفظ میں "i" کی لمبی آواز ہے؟', en:'Which has long "i" sound?',
      a:'fish', b:'six', c:'five', d:'big', ans:'C' },
    { id:'ENG-L1-052', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'4 کے بعد کا نمبر (لفظ میں)؟', en:'Number after 4 in words?',
      a:'hide', b:'bite', c:'file', d:'five', ans:'D' },
    { id:'ENG-L1-053', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'دانتوں سے کھانا؟', en:'To use your teeth to eat?',
      a:'hide', b:'five', c:'bite', d:'file', ans:'C' },
    { id:'ENG-L1-054', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'کاغذ فولڈر میں رکھنا؟', en:'To keep papers in a folder?',
      a:'five', b:'hide', c:'file', d:'bite', ans:'C' },
    { id:'ENG-L1-055', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'k + i + t + e = ؟', en:'k + i + t + e = ?',
      a:'kit', b:'kite', c:'kate', d:'cute', ans:'B' },
    { id:'ENG-L1-056', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'کون سے لفظ میں لمبی "i" ہے؟', en:'Which has long "i"?',
      a:'bit', b:'sit', c:'kite', d:'fit', ans:'C' },
    { id:'ENG-L1-057', level:1, subject:'English', topic:'long_vowel_i', difficulty:1,
      ur:'جہاں کوئی نہ دیکھے وہاں جانا؟', en:'To go where no one can find you?',
      a:'file', b:'bite', c:'five', d:'hide', ans:'D' },

    // ── long_vowel_o ──
    { id:'ENG-L1-058', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'کون سے لفظ میں "o" کی لمبی آواز ہے؟', en:'Which has long "o" sound?',
      a:'frog', b:'dog', c:'rose', d:'ox', ans:'C' },
    { id:'ENG-L1-059', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'سرخ پھول؟', en:'A red flower?',
      a:'hose', b:'bone', c:'rope', d:'rose', ans:'D' },
    { id:'ENG-L1-060', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'سونگھنے کا عضو؟', en:'You smell with your?',
      a:'rope', b:'nose', c:'hose', d:'bone', ans:'B' },
    { id:'ENG-L1-061', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'کتا اسے چباتا ہے؟', en:'A dog loves to chew a?',
      a:'rose', b:'hose', c:'rope', d:'bone', ans:'D' },
    { id:'ENG-L1-062', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'پودوں کو پانی دینے کے لیے؟', en:'You use it to water plants?',
      a:'rose', b:'bone', c:'hose', d:'nose', ans:'C' },
    { id:'ENG-L1-063', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'r + o + s + e = ؟', en:'r + o + s + e = ?',
      a:'rose', b:'rope', c:'rode', d:'role', ans:'A' },
    { id:'ENG-L1-064', level:1, subject:'English', topic:'long_vowel_o', difficulty:1,
      ur:'کون سے لفظ میں لمبی "o" ہے؟', en:'Which has long "o"?',
      a:'hot', b:'box', c:'dog', d:'rope', ans:'D' },

    // ── long_vowel_u ──
    { id:'ENG-L1-065', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'کون سے لفظ میں "u" کی لمبی آواز ہے؟', en:'Which has long "u" sound?',
      a:'cup', b:'bus', c:'cube', d:'sun', ans:'C' },
    { id:'ENG-L1-066', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'مربع شکل کا ٹھوس جسم؟', en:'A 3D box shape?',
      a:'tube', b:'mule', c:'cube', d:'dune', ans:'C' },
    { id:'ENG-L1-067', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'پھونک کر بجانے والا ساز؟', en:'A musical instrument you blow?',
      a:'cube', b:'dune', c:'mule', d:'flute', ans:'D' },
    { id:'ENG-L1-068', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'ریگستان میں ریت کی پہاڑی؟', en:'A sand hill in the desert?',
      a:'cube', b:'flute', c:'mule', d:'dune', ans:'D' },
    { id:'ENG-L1-069', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'ٹوتھ پیسٹ اس میں آتا ہے؟', en:'Toothpaste comes in a?',
      a:'cube', b:'dune', c:'flute', d:'tube', ans:'D' },
    { id:'ENG-L1-070', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'c + u + b + e = ؟', en:'c + u + b + e = ?',
      a:'cub', b:'cube', c:'cup', d:'cut', ans:'B' },
    { id:'ENG-L1-071', level:1, subject:'English', topic:'long_vowel_u', difficulty:1,
      ur:'کون سے لفظ میں لمبی "u" ہے؟', en:'Which has long "u"?',
      a:'cup', b:'run', c:'flute', d:'sun', ans:'C' },

    // ── alphabet_letters ──
    { id:'ENG-L1-072', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'انگریزی حروف تہجی میں کتنے حروف ہیں؟', en:'How many letters in English alphabet?',
      a:'24', b:'25', c:'26', d:'27', ans:'C' },
    { id:'ENG-L1-073', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'D کے بعد کون سا حرف آتا ہے؟', en:'Which letter comes after D?',
      a:'C', b:'E', c:'F', d:'B', ans:'B' },
    { id:'ENG-L1-074', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'G سے پہلے کون سا حرف آتا ہے؟', en:'Which letter comes before G?',
      a:'F', b:'H', c:'E', d:'I', ans:'A' },
    { id:'ENG-L1-075', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'حروف تہجی کا پہلا حرف؟', en:'First letter of alphabet?',
      a:'B', b:'Z', c:'A', d:'E', ans:'C' },
    { id:'ENG-L1-076', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'حروف تہجی کا آخری حرف؟', en:'Last letter of alphabet?',
      a:'Y', b:'X', c:'W', d:'Z', ans:'D' },
    { id:'ENG-L1-077', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'بڑا B چھوٹے کے ساتھ ملتا ہے؟', en:'Capital B matches with small?',
      a:'d', b:'b', c:'p', d:'q', ans:'B' },
    { id:'ENG-L1-078', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'بڑا D چھوٹے کے ساتھ ملتا ہے؟', en:'Capital D matches with small?',
      a:'b', b:'p', c:'d', d:'q', ans:'C' },
    { id:'ENG-L1-079', level:1, subject:'English', topic:'alphabet_letters', difficulty:1,
      ur:'E اور G کے درمیان کون سا حرف ہے؟', en:'Which letter comes between E and G?',
      a:'D', b:'H', c:'F', d:'I', ans:'C' },

    // ── vowels_consonants ──
    { id:'ENG-L1-080', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'کون سا حرف vowel ہے؟', en:'Which is a vowel?',
      a:'B', b:'C', c:'D', d:'A', ans:'D' },
    { id:'ENG-L1-081', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'کتنے vowels ہیں؟', en:'How many vowels are there?',
      a:'3', b:'4', c:'5', d:'6', ans:'C' },
    { id:'ENG-L1-082', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'کون سا vowel نہیں ہے؟', en:'Which is NOT a vowel?',
      a:'A', b:'E', c:'B', d:'I', ans:'C' },
    { id:'ENG-L1-083', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'Vowels کون سے ہیں؟', en:'The vowels are?',
      a:'a,b,c,d,e', b:'a,e,i,o,u', c:'b,c,d,f,g', d:'a,e,i,u,y', ans:'B' },
    { id:'ENG-L1-084', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'"U" کیا ہے؟', en:'"U" is a?',
      a:'consonant', b:'vowel', c:'number', d:'digraph', ans:'B' },
    { id:'ENG-L1-085', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'کون سا حرف consonant ہے؟', en:'Which letter is a consonant?',
      a:'O', b:'A', c:'M', d:'I', ans:'C' },
    { id:'ENG-L1-086', level:1, subject:'English', topic:'vowels_consonants', difficulty:1,
      ur:'جو لفظ vowel سے شروع ہو؟', en:'Which word starts with a vowel?',
      a:'cat', b:'ant', c:'bat', d:'mat', ans:'B' },

    // ── digraphs ──
    { id:'ENG-L1-087', level:1, subject:'English', topic:'digraphs', difficulty:1,
      ur:'Digraph کیا ہے؟', en:'A digraph is?',
      a:'ایک حرف', b:'دو حروف جو ایک آواز بناتے ہیں', c:'تین حروف', d:'ایک vowel', ans:'B' },
    { id:'ENG-L1-088', level:1, subject:'English', topic:'digraphs', difficulty:1,
      ur:'"fish" میں "sh" کیا ہے؟', en:'"sh" in "fish" is?',
      a:'vowel', b:'consonant', c:'digraph', d:'blend', ans:'C' },
    { id:'ENG-L1-089', level:1, subject:'English', topic:'digraphs', difficulty:1,
      ur:'"dish" اور "fish" دونوں کس پر ختم ہوتے ہیں؟', en:'"dish" and "fish" both end with?',
      a:'sh', b:'ch', c:'th', d:'ph', ans:'A' },
    { id:'ENG-L1-090', level:1, subject:'English', topic:'digraphs', difficulty:1,
      ur:'کون سے لفظ میں digraph ہے؟', en:'Which word has a digraph?',
      a:'cat', b:'fish', c:'bat', d:'rat', ans:'B' },
    { id:'ENG-L1-091', level:1, subject:'English', topic:'digraphs', difficulty:2,
      ur:'"sh" کتنی آوازیں بناتا ہے؟', en:'How many sounds does "sh" make?',
      a:'two', b:'three', c:'one', d:'four', ans:'C' },
    { id:'ENG-L1-092', level:1, subject:'English', topic:'digraphs', difficulty:2,
      ur:'"th" digraph کیوں ہے؟', en:'"th" is a digraph because?',
      a:'اس میں دو vowels ہیں', b:'دو حروف ایک آواز بناتے ہیں', c:'اس میں تین حروف ہیں', d:'t سے شروع ہوتا ہے', ans:'B' },

    // ═══════════════════════════════════════════
    //  URDU — Level 1
    // ═══════════════════════════════════════════

    // ── haroof_recognition ──
    { id:'URD-L1-001', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:1,
      ur:'"کتاب" میں کتنے حروف ہیں؟', en:'How many letters in "kitaab"?',
      a:'3', b:'5', c:'4', d:'6', ans:'C' },
    { id:'URD-L1-002', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:1,
      ur:'"پودا" میں کتنے حروف ہیں؟', en:'How many letters in "poda"?',
      a:'3', b:'4', c:'5', d:'2', ans:'B' },
    { id:'URD-L1-003', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:1,
      ur:'"انار" میں کتنے حروف ہیں؟', en:'How many letters in "anar"?',
      a:'3', b:'4', c:'5', d:'2', ans:'B' },
    { id:'URD-L1-004', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:1,
      ur:'"چوٹ" میں کتنے حروف ہیں؟', en:'How many letters in "chot"?',
      a:'2', b:'3', c:'4', d:'5', ans:'B' },
    { id:'URD-L1-005', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:1,
      ur:'"لڑکی" میں کتنے حروف ہیں؟', en:'How many letters in "larki"?',
      a:'3', b:'4', c:'5', d:'6', ans:'B' },
    { id:'URD-L1-006', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:2,
      ur:'ک + ت + ا + ب = ؟', en:'K + T + A + B joined = ?',
      a:'کاتب', b:'کتاب', c:'کتب', d:'کباب', ans:'B' },
    { id:'URD-L1-007', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:2,
      ur:'"سلام" میں کتنے حروف ہیں؟', en:'How many letters in "salaam"?',
      a:'3', b:'4', c:'5', d:'6', ans:'B' },
    { id:'URD-L1-008', level:1, subject:'Urdu', topic:'haroof_recognition', difficulty:2,
      ur:'"سورج" میں کتنے حروف ہیں؟', en:'How many letters in "suraj"?',
      a:'3', b:'4', c:'5', d:'6', ans:'B' },

    // ── lafz_poda ──
    { id:'URD-L1-009', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:1,
      ur:'"پودا" کیا ہے؟', en:'What is a "poda" (plant)?',
      a:'جانور', b:'پودا', c:'پانی', d:'پتھر', ans:'B' },
    { id:'URD-L1-010', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:1,
      ur:'پودے کو بڑھنے کے لیے کیا چاہیے؟', en:'What does a plant need to grow?',
      a:'پتھر', b:'پانی', c:'ریت', d:'لوہا', ans:'B' },
    { id:'URD-L1-011', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:1,
      ur:'پودے کی جڑ کیا کرتی ہے؟', en:'What does the root of a plant do?',
      a:'پھل دیتی ہے', b:'سایہ دیتی ہے', c:'پانی لیتی ہے', d:'رنگ دیتی ہے', ans:'C' },
    { id:'URD-L1-012', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:1,
      ur:'سورج کی روشنی پودوں کے لیے؟', en:'Sunlight for plants is?',
      a:'نقصاندہ ہے', b:'ضروری ہے', c:'بیکار ہے', d:'خطرناک ہے', ans:'B' },
    { id:'URD-L1-013', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:1,
      ur:'پودے کا کون سا حصہ پانی اندر لیتا ہے؟', en:'Which part of plant absorbs water?',
      a:'پھل', b:'پتے', c:'جڑ', d:'پھول', ans:'C' },
    { id:'URD-L1-014', level:1, subject:'Urdu', topic:'lafz_poda', difficulty:2,
      ur:'پودا کیا بناتا ہے جو ہم کھاتے ہیں؟', en:'What does a plant produce that we eat?',
      a:'دودھ', b:'پھل اور سبزی', c:'پانی', d:'لوہا', ans:'B' },

    // ── lafz_anar ──
    { id:'URD-L1-015', level:1, subject:'Urdu', topic:'lafz_anar', difficulty:1,
      ur:'"انار" کیا ہے؟', en:'What is "anar"?',
      a:'سبزی', b:'پھل', c:'جانور', d:'پودا', ans:'B' },
    { id:'URD-L1-016', level:1, subject:'Urdu', topic:'lafz_anar', difficulty:1,
      ur:'انار کا رنگ کیا ہوتا ہے؟', en:'What color is a pomegranate?',
      a:'پیلا', b:'نیلا', c:'سرخ', d:'سفید', ans:'C' },
    { id:'URD-L1-017', level:1, subject:'Urdu', topic:'lafz_anar', difficulty:1,
      ur:'انار کھایا جاتا ہے یا پہنا جاتا ہے؟', en:'Pomegranate is eaten or worn?',
      a:'پہنا', b:'کھایا', c:'لکھا', d:'پڑھا', ans:'B' },
    { id:'URD-L1-018', level:1, subject:'Urdu', topic:'lafz_anar', difficulty:1,
      ur:'انار کہاں اگتا ہے؟', en:'Where does pomegranate grow?',
      a:'پانی میں', b:'پودے پر', c:'آسمان میں', d:'زمین کے اندر', ans:'B' },
    { id:'URD-L1-019', level:1, subject:'Urdu', topic:'lafz_anar', difficulty:2,
      ur:'"انار" کا پہلا حرف؟', en:'First letter of "anar"?',
      a:'ن', b:'ر', c:'ا', d:'م', ans:'C' },

    // ── lafz_chot ──
    { id:'URD-L1-020', level:1, subject:'Urdu', topic:'lafz_chot', difficulty:1,
      ur:'"چوٹ" کا مطلب کیا ہے؟', en:'What does "chot" mean?',
      a:'خوشی', b:'تکلیف', c:'کھانا', d:'پانی', ans:'B' },
    { id:'URD-L1-021', level:1, subject:'Urdu', topic:'lafz_chot', difficulty:1,
      ur:'چوٹ لگنے پر آپ کیا کرتے ہیں؟', en:'When you get hurt, you?',
      a:'ناچتے ہیں', b:'ڈاکٹر کے پاس جاتے ہیں', c:'سوتے ہیں', d:'کھیلتے ہیں', ans:'B' },
    { id:'URD-L1-022', level:1, subject:'Urdu', topic:'lafz_chot', difficulty:1,
      ur:'چوٹ لگنے پر کیا ہوتا ہے؟', en:'When hurt, what happens?',
      a:'ہنسی آتی ہے', b:'درد ہوتا ہے', c:'بھوک لگتی ہے', d:'نیند آتی ہے', ans:'B' },
    { id:'URD-L1-023', level:1, subject:'Urdu', topic:'lafz_chot', difficulty:2,
      ur:'"چوٹ" کا ہم معنی لفظ؟', en:'Word similar in meaning to "chot"?',
      a:'خوشی', b:'درد', c:'مزہ', d:'خوبصورتی', ans:'B' },

    // ── lafz_larki ──
    { id:'URD-L1-024', level:1, subject:'Urdu', topic:'lafz_larki', difficulty:1,
      ur:'"لڑکی" کا مطلب کیا ہے؟', en:'What does "larki" mean?',
      a:'لڑکا', b:'عورت', c:'لڑکی', d:'بچہ', ans:'C' },
    { id:'URD-L1-025', level:1, subject:'Urdu', topic:'lafz_larki', difficulty:1,
      ur:'لڑکی کی جمع کیا ہے؟', en:'Plural of "larki" (girl)?',
      a:'لڑکا', b:'لڑکیاں', c:'لڑکے', d:'بچے', ans:'B' },
    { id:'URD-L1-026', level:1, subject:'Urdu', topic:'lafz_larki', difficulty:1,
      ur:'لڑکی کا مخالف؟', en:'Opposite of girl?',
      a:'عورت', b:'ماں', c:'لڑکا', d:'بہن', ans:'C' },
    { id:'URD-L1-027', level:1, subject:'Urdu', topic:'lafz_larki', difficulty:2,
      ur:'ایک لڑکی ہے، دو ___ ہیں', en:'One girl, two ___?',
      a:'لڑکا', b:'لڑکیاں', c:'لڑکے', d:'بچے', ans:'B' },

    // ── jandaar_be_jaan ──
    { id:'URD-L1-028', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'شیر کیا ہے؟', en:'A lion is?',
      a:'بے جان', b:'جاندار', c:'پتھر', d:'پانی', ans:'B' },
    { id:'URD-L1-029', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'کتاب کیا ہے؟', en:'A book is?',
      a:'جاندار', b:'بے جان', c:'جانور', d:'پودا', ans:'B' },
    { id:'URD-L1-030', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'پودا کیا ہے؟', en:'A plant is?',
      a:'بے جان', b:'جاندار', c:'پتھر', d:'لکڑی', ans:'B' },
    { id:'URD-L1-031', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'پانی کیا ہے؟', en:'Water is?',
      a:'جاندار', b:'جانور', c:'بے جان', d:'پودا', ans:'C' },
    { id:'URD-L1-032', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'بلی کیا ہے؟', en:'A cat is?',
      a:'بے جان', b:'پتھر', c:'جاندار', d:'لکڑی', ans:'C' },
    { id:'URD-L1-033', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:1,
      ur:'کرسی کیا ہے؟', en:'A chair is?',
      a:'جاندار', b:'جانور', c:'پودا', d:'بے جان', ans:'D' },
    { id:'URD-L1-034', level:1, subject:'Urdu', topic:'jandaar_be_jaan', difficulty:2,
      ur:'آم کیا ہے؟', en:'A mango (tree) is?',
      a:'بے جان', b:'جاندار', c:'پتھر', d:'پانی', ans:'B' },

    // ── short_vowels_urdu (زیر/زبر/پیش) ──
    { id:'URD-L1-035', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:1,
      ur:'زبر کی آواز کیسی ہے؟', en:'What sound does "zabar" make?',
      a:'اِ (i)', b:'اَ (a)', c:'اُ (u)', d:'آ (aa)', ans:'B' },
    { id:'URD-L1-036', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:1,
      ur:'زیر کی آواز کیسی ہے؟', en:'What sound does "zer" make?',
      a:'اَ (a)', b:'اُ (u)', c:'اِ (i)', d:'آ (aa)', ans:'C' },
    { id:'URD-L1-037', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:1,
      ur:'پیش کی آواز کیسی ہے؟', en:'What sound does "pesh" make?',
      a:'اَ (a)', b:'اِ (i)', c:'آ (aa)', d:'اُ (u)', ans:'D' },
    { id:'URD-L1-038', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:2,
      ur:'"بَس" میں ب پر کون سی حرکت ہے؟', en:'Which harkat is on "b" in "bas"?',
      a:'زیر', b:'پیش', c:'زبر', d:'جزم', ans:'C' },
    { id:'URD-L1-039', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:2,
      ur:'"بِلّی" میں ب پر کون سی حرکت ہے؟', en:'Which harkat is on "b" in "billi"?',
      a:'زبر', b:'پیش', c:'زیر', d:'جزم', ans:'C' },
    { id:'URD-L1-040', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:1,
      ur:'حرکتیں کتنی ہیں؟', en:'How many short vowel marks (harkat) are there?',
      a:'2', b:'3', c:'4', d:'5', ans:'B' },
    { id:'URD-L1-041', level:1, subject:'Urdu', topic:'short_vowels_urdu', difficulty:2,
      ur:'"دودھ" میں د پر کون سی حرکت ہے؟', en:'Which harkat is on "d" in "doodh"?',
      a:'زیر', b:'زبر', c:'پیش', d:'جزم', ans:'C' },

    // ── sunlight_benefits ──
    { id:'URD-L1-042', level:1, subject:'Urdu', topic:'sunlight_benefits', difficulty:1,
      ur:'سورج کی روشنی سے کیا ملتا ہے؟', en:'What do we get from sunlight?',
      a:'اندھیرا', b:'روشنی', c:'بارش', d:'ٹھنڈک', ans:'B' },
    { id:'URD-L1-043', level:1, subject:'Urdu', topic:'sunlight_benefits', difficulty:1,
      ur:'سورج کب نکلتا ہے؟', en:'When does the sun rise?',
      a:'رات کو', b:'دوپہر کو', c:'صبح کو', d:'شام کو', ans:'C' },
    { id:'URD-L1-044', level:1, subject:'Urdu', topic:'sunlight_benefits', difficulty:1,
      ur:'سورج کی روشنی پودوں کے لیے کیا ہے؟', en:'Sunlight is ___ for plants?',
      a:'نقصاندہ', b:'ضروری', c:'بیکار', d:'خطرناک', ans:'B' },

    // ── hamd ──
    { id:'URD-L1-045', level:1, subject:'Urdu', topic:'hamd', difficulty:1,
      ur:'حمد کس کی تعریف میں لکھی جاتی ہے؟', en:'Hamd is written in praise of?',
      a:'استاد', b:'ماں', c:'اللہ', d:'نبی', ans:'C' },
    { id:'URD-L1-046', level:1, subject:'Urdu', topic:'hamd', difficulty:1,
      ur:'حمد کیا ہے؟', en:'What is "hamd"?',
      a:'کہانی', b:'اللہ کی تعریف', c:'کھیل', d:'گانا', ans:'B' },

    // ── wood_uses ──
    { id:'URD-L1-047', level:1, subject:'Urdu', topic:'wood_uses', difficulty:1,
      ur:'کرسی کس چیز سے بنتی ہے؟', en:'A chair is made of?',
      a:'پتھر', b:'لکڑی', c:'لوہا', d:'مٹی', ans:'B' },
    { id:'URD-L1-048', level:1, subject:'Urdu', topic:'wood_uses', difficulty:1,
      ur:'میز کس چیز سے بنتی ہے؟', en:'A table is made of?',
      a:'مٹی', b:'پتھر', c:'لکڑی', d:'کپڑا', ans:'C' },
    { id:'URD-L1-049', level:1, subject:'Urdu', topic:'wood_uses', difficulty:1,
      ur:'کون سی چیز لکڑی سے بنتی ہے؟', en:'Which thing is made of wood?',
      a:'شیشہ', b:'لوہا', c:'کرسی', d:'کپڑا', ans:'C' },

  ];

  console.log(`Inserting ${questions.length} Level 1 questions...`);

  for (const q of questions) {
    await pool.query(`
      INSERT INTO questions
        (question_id, level, subject, topic_tag, q_text_urdu, q_text_english,
         option_a, option_b, option_c, option_d, correct_option, difficulty)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
      ON CONFLICT (question_id) DO NOTHING
    `, [q.id, q.level, q.subject, q.topic, q.ur, q.en,
        q.a, q.b, q.c, q.d, q.ans, q.difficulty]);
  }

  const result = await pool.query('SELECT subject, COUNT(*) FROM questions WHERE level=1 GROUP BY subject');
  console.log('\n✅  Level 1 Question Bank Complete:');
  result.rows.forEach(r => console.log(`   ${r.subject}: ${r.count} questions`));
  await pool.end();
}

seedQuestions().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});